services:
  app: 
    build:
      context: .
    ports:
      - "8000:8000"
    env_file: &env_file
      - .env
    volumes:
      - ./app:/app
    environment:
      - DB_HOSTNAME=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine
    env_file: *env_file
    environment:
      - DB_HOST=db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - shopnova_db_data:/var/lib/postgresql/data

volumes:
  shopnova_db_data:
  shopnova_static_data: