[tool.black]
line-length = 100
target-version = ['py310']
skip-string-normalization = false
exclude = '''
/(
    migrations
  | __pycache__
  | \.venv
  | build
  | dist
  | manage.py
  | settings.py
)/
'''